language: python
# TODO `dist` and `sudo` needed temporarily for python3.7 support.
# Waiting on https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial
sudo: true
python:
  - "3.7"

install:
  - "pip install -e .[test]"
  - "pip install coveralls"
  - "pip install pycodestyle"
  - "pip install pyflakes"
  - "pip install pylint"
  - "pip install sphinx"

script:
  - "coverage run --source=cheat_server setup.py test"
  - "pycodestyle cheat_server setup.py"
  - "pyflakes cheat_server setup.py"
  - "pylint -E cheat_server setup.py"

after_success:
  - "coveralls"

before_deploy:
  - "make -C docs html"
